"""AI-generated-image detection via Hugging Face inference API.

Complements the ELA/EXIF manipulation forensics with a trained classifier
that answers a different question: was this image generated by AI
(GAN/diffusion) rather than captured by a camera? Requires a free
HF_API_KEY; silently unavailable without one so ELA-only analysis still works.
"""

from __future__ import annotations

import logging
import os

import requests

logger = logging.getLogger(__name__)

HF_MODELS = [
    "Organika/sdxl-detector",
    "umm-maybe/AI-image-detector",
]
HF_URL = "https://router.huggingface.co/hf-inference/models/{model}"
REQUEST_TIMEOUT = 30

AI_LABEL_HINTS = ("artificial", "ai", "fake", "generated", "sdxl")


def detect_ai_image(image_bytes: bytes) -> dict | None:
    """Return {'ai_probability': float, 'model': str} or None if unavailable."""
    api_key = os.getenv("HF_API_KEY", "").strip()
    if not api_key:
        return None

    for model in HF_MODELS:
        try:
            response = requests.post(
                HF_URL.format(model=model),
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "image/jpeg",
                    "X-Wait-For-Model": "true",
                },
                data=image_bytes,
                timeout=REQUEST_TIMEOUT,
            )
            if response.status_code != 200:
                logger.info("HF model %s returned %s", model, response.status_code)
                continue
            predictions = response.json()
            if not isinstance(predictions, list):
                continue
            for prediction in predictions:
                label = str(prediction.get("label", "")).lower()
                if any(hint in label for hint in AI_LABEL_HINTS):
                    return {
                        "ai_probability": round(float(prediction.get("score", 0.0)), 4),
                        "model": model,
                    }
            # Labels present but none AI-flavored — treat top 'human'/'real'
            # label as the complement
            top = predictions[0] if predictions else {}
            if str(top.get("label", "")).lower() in ("human", "real", "authentic"):
                return {
                    "ai_probability": round(1.0 - float(top.get("score", 0.0)), 4),
                    "model": model,
                }
        except Exception as exc:
            logger.info("HF model %s failed: %s", model, exc)
    return None
